### ISSUE TITLE
Module Request: Character works

### ISSUE THREAD

**Issue by Josh-clarke95** [bitfocus/companion-module-agf-characterworks#1]
Describe the feature
Control Character works to be able to play stop and finish motions 

Is this platform dependent (windows, mac, ..)?
only windows based

If documentation is required to implement, do you know where to find it?
https://www.chrworks.com/help/
Then under the remote control section of the manual 

Usecases
I use it name straps and bugs on events would not nice to play with a button rather than i mouse click

**Comment by ewettach** [comment]
I have been working on the requested grid execute feature request.  Unfortunately I am hitting a road block due to the way that the JSON POST request is being sent to Characterworks, it encloses everything in quotes (which is a good thing).  If you notice for all commands Characterworks wants the double quotes, however on the grid cell it does not.  I have not found a solution yet to be able to send just the cell coordinates with no double quotes.

**Comment by ewettach** [comment]
@spiritimk I have now added support in version 1.0.2 for calling grid buttons.
